services:
  model-service:
    image: ghcr.io/remla23-team3/model-service:latest
    environment:
      - DEBUG=0
    ports:
      - 6789:6789
    volumes:
      - ./model-training/:/usr/share/model-training/data
  app:
    build: https://github.com/remla23-team3/app.git#main
    ports:
      - 8081:8081
    environment:
      - DEBUG=0
    volumes:
      - ./app/:/usr/share/app/data
