# docker-compose.yml
services:
  modelService:
    image: ghcr.io/remla23-team3/model-service:latest
    ports:
      - 6789:6789
    # networks: 
    #   - my-shared-network
  app:
    build: https://github.com/remla23-team3/app.git#basic-app
    ports:
      - 8080:8081
    # networks: 
    #   - my-shared-network
    depends_on:
      - modelService
# networks:
#   my-shared-network: {}