# docker-compose.yml
services:
  app:
    build: https://github.com/remla23-team3/app.git#basic-app
    image: app-image-proba
    ports:
      - 8080:8081
  modelService:
    build: https://github.com/remla23-team3/model-service.git#add-flask-webservice
    image: model-service
    ports:
      - 8082:6789