# kubernetes.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model
  template:
    metadata:
      labels:
        app: model
    spec:
      containers:
        - name: model-service
          image: ghcr.io/remla23-team3/model-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 6789
          env:
            - name: NAMEKEY
              valueFrom:
                configMapKeyRef:
                  name: model-configmap
                  key: namekey
            - name: PASS
              valueFrom:
                secretKeyRef:
                  name: model-secret
                  key: pass
          volumeMounts:
            - name: model-volume
              mountPath: /data_model_in/
      volumes:
        - name: model-volume
          hostPath:
            path: /data_model_out/
      imagePullSecrets:
        - name: registry-credentials
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: model-configmap
data:
  namekey: Model
---
apiVersion: v1
kind: Secret
metadata:
  name: model-secret
data:
  pass: YmFy
---
apiVersion: v1
kind: Service
metadata:
  name: model-service
spec:
  type: LoadBalancer
  selector:
    app: model
  ports:
    - protocol: TCP
      port: 6789
      targetPort: 6789
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: ghcr.io/remla23-team3/app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: NAMEKEY
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: namekey
            - name: PASS
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: pass
          volumeMounts:
            - name: app-volume
              mountPath: /data_app_in/
      volumes:
        - name: app-volume
          hostPath:
            path: /data_app_out/
      imagePullSecrets:
        - name: registry-credentials
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
data:
  namekey: App
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  pass: YmFy
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: LoadBalancer
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-service
                port:
                  number: 8081
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: model-service
                port:
                  number: 6789
