{
 "title": "Restaurant Dashboard v2",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "How accurate have we been?",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "remla23_team3:accuracy" }
   ]
  },
  {
   "title": "Ratio of users leaving feedback past 10 minutes",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg_over_time(remla23_team3:feedback_percentage[10m])"
    }
   ]
  },
  {
   "title": "Number of requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "remla23_team3:num_total_requests{method=\"post\",code=\"200\"}"
    }
   ]
  }
 ]
}