name: Deploy

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Parse major, minor and path from version tag
        run: |
          VERSION=${GITHUB_REF:11}
          MAJOR=`echo "$VERSION" | cut -d . -f 1`
          MINOR=`echo "$VERSION" | cut -d . -f 2`
          PATCH=`echo "$VERSION" | cut -d . -f 3`
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "major=$MAJOR" >> $GITHUB_ENV
          echo "minor=$MINOR" >> $GITHUB_ENV
          echo "patch=$PATCH" >> $GITHUB_ENV
      
      - name: Deploy
        uses: deliverybot/helm@v1
        with:
          release: nginx
          track: stable
          namespace: default
          chart: remla23-team3
          version: ${{ env.major }}.${{ env.minor }}.${{ env.patch }}
          token: ${{ secrets.GITHUB_TOKEN }}
